openapi: 3.0.3
info:
  title: Finance Manager API
  version: 1.0.0
  description: API para gerenciamento financeiro

servers:
  - url: "{apiUrl}/api"
    description: API Server
    variables:
      apiUrl:
        default: http://localhost:5173
        description: Base URL from VITE_API_URL env var

paths:
  /auth/login:
    $ref: "./paths/auth.yaml#/login"
  /auth/register:
    $ref: "./paths/auth.yaml#/register"
  /auth/me:
    $ref: "./paths/auth.yaml#/me"
  /financeManager/income/list:
    $ref: "./paths/income.yaml#/list"
  /financeManager/income:
    $ref: "./paths/income.yaml#/create"
  /financeManager/payment/list:
    $ref: "./paths/payment.yaml#/list"
  /financeManager/payment:
    $ref: "./paths/payment.yaml#/create"
  /financeManager/debt/list:
    $ref: "./paths/debt.yaml#/list"
  /financeManager/debt:
    $ref: "./paths/debt.yaml#/create"

components:
  schemas:
    LoginRequest:
      $ref: "./schemas/auth.yaml#/LoginRequest"
    RegisterRequest:
      $ref: "./schemas/auth.yaml#/RegisterRequest"
    UserResponse:
      $ref: "./schemas/auth.yaml#/UserResponse"
    AuthResponse:
      $ref: "./schemas/auth.yaml#/AuthResponse"
    ListIncomesFilters:
      $ref: "./schemas/income.yaml#/ListIncomesFilters"
    Income:
      $ref: "./schemas/income.yaml#/Income"
    CreateIncomeRequest:
      $ref: "./schemas/income.yaml#/CreateIncomeRequest"
    ListPaymentsFilters:
      $ref: "./schemas/payment.yaml#/ListPaymentsFilters"
    Payment:
      $ref: "./schemas/payment.yaml#/Payment"
    CreatePaymentRequest:
      $ref: "./schemas/payment.yaml#/CreatePaymentRequest"
    CreateDebtRequest:
      $ref: "./schemas/debt.yaml#/CreateDebtRequest"
    DebtFilters:
      $ref: "./schemas/debt.yaml#/DebtFilters"
    Debt:
      $ref: "./schemas/debt.yaml#/Debt"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
